// <auto-generated />
using System;
using HumanResourceManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResourceManagement.Migrations
{
    [DbContext(typeof(HumanResourceManagementDbContext))]
    partial class HumanResourceManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanResourceManagement.Models.ChamCong", b =>
                {
                    b.Property<string>("MaChamCong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GioRaLam")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GioVaoLam")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LichLamId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("SoGioLamThem")
                        .HasColumnType("float");

                    b.Property<double>("SoGioLamViec")
                        .HasColumnType("float");

                    b.Property<double>("SoGioNghiKhongPhep")
                        .HasColumnType("float");

                    b.Property<double>("SoGioNghiPhep")
                        .HasColumnType("float");

                    b.Property<double>("TongGioLam")
                        .HasColumnType("float");

                    b.HasKey("MaChamCong");

                    b.HasIndex("LichLamId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("ChamCongs");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTaCongViec")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("MucLuong")
                        .HasColumnType("float");

                    b.Property<string>("PhongBanId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChucVu");

                    b.HasIndex("PhongBanId");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.HieuSuat", b =>
                {
                    b.Property<string>("MaHieuSuat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DanhGiaHieuSuat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KeHoachPhatTrien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KyDanhGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MucTieuHieuSuat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NguoiDanhGia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhanHoi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaHieuSuat");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HieuSuats");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.HopDong", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoiDungHopDong")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ThoiHanHopDong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThaiHopDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.LichLam", b =>
                {
                    b.Property<string>("MaLichLam")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CaLamViec")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GioBatDau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GioKetThuc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTaCongViec")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayLam")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichLam");

                    b.ToTable("LichLams");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.LichLamNhanVien", b =>
                {
                    b.Property<string>("NhanVienId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LichLamId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NhanVienId", "LichLamId");

                    b.HasIndex("LichLamId");

                    b.ToTable("LichLamNhanViens");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.Luong", b =>
                {
                    b.Property<string>("MaLuong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("CacKhoanKhauTru")
                        .HasColumnType("float");

                    b.Property<double>("LuongCoBan")
                        .HasColumnType("float");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("ThuNhapRong")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<double>("TongTienPhuCap")
                        .HasColumnType("float");

                    b.Property<double>("TongTienThuong")
                        .HasColumnType("float");

                    b.HasKey("MaLuong");

                    b.HasIndex("NhanVienId");

                    b.ToTable("Luongs");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.NghiVang", b =>
                {
                    b.Property<string>("MaNghiVang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LichLamId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiNghiVang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoNgayNghi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNghiVang");

                    b.HasIndex("LichLamId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("NghiVangs");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ChucVuId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("MucLuong")
                        .HasColumnType("float");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiQuanLy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhongBanId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TonGiao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.PhongBan", b =>
                {
                    b.Property<string>("SoPhong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NguoiQuanLy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SoPhong");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.PhuCap", b =>
                {
                    b.Property<string>("MaPhuCap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("SoTienPhuCap")
                        .HasColumnType("float");

                    b.Property<string>("TanSuat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenPhuCap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhuCap");

                    b.ToTable("PhuCaps");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.PhuCapNhanVien", b =>
                {
                    b.Property<string>("NhanVienId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhuCapId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NhanVienId", "PhuCapId");

                    b.HasIndex("PhuCapId");

                    b.ToTable("PhuCapNhanViens");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.Thue", b =>
                {
                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("MucThuNhapChiuThue")
                        .HasColumnType("float");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoNguoiPhuThuoc")
                        .HasColumnType("int");

                    b.Property<double>("ThueSuat")
                        .HasColumnType("float");

                    b.Property<double>("ThueThuNhapCaNhanThucTe")
                        .HasColumnType("float");

                    b.Property<string>("TrangThaiHonNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSoThue");

                    b.HasIndex("NhanVienId");

                    b.ToTable("Thues");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.Thuong", b =>
                {
                    b.Property<string>("MaKhoanThuong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LyDoKhenThuong")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayKhenThuong")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoTienThuong")
                        .HasColumnType("float");

                    b.HasKey("MaKhoanThuong");

                    b.ToTable("Thuongs");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.ThuongNhanVien", b =>
                {
                    b.Property<string>("NhanVienId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThuongId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NhanVienId", "ThuongId");

                    b.HasIndex("ThuongId");

                    b.ToTable("ThuongNhanViens");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.TrinhDoHocVan", b =>
                {
                    b.Property<string>("MaTrinhDo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BangCap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NameTotNghiep")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenTrinhDoHocVan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTruong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTrinhDo");

                    b.HasIndex("NhanVienId");

                    b.ToTable("TrinhDoHocVans");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.ChamCong", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.LichLam", "LichLam")
                        .WithMany("ChamCongs")
                        .HasForeignKey("LichLamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("ChamCongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichLam");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.ChucVu", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.PhongBan", "PhongBan")
                        .WithMany("ChucVus")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.HieuSuat", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("HieuSuats")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.HopDong", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.LichLamNhanVien", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.LichLam", "LichLam")
                        .WithMany("LichLamNhanViens")
                        .HasForeignKey("LichLamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("LichLamNhanViens")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichLam");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.Luong", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("Luongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.NghiVang", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.LichLam", "LichLam")
                        .WithMany("NghiVangs")
                        .HasForeignKey("LichLamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("NghiVangs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichLam");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.NhanVien", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("HumanResourceManagement.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.PhuCapNhanVien", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("PhuCapNhanViens")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagement.Models.PhuCap", "PhuCap")
                        .WithMany("PhuCapNhanViens")
                        .HasForeignKey("PhuCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("PhuCap");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.Thue", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("Thues")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.ThuongNhanVien", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("ThuongNhanViens")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanResourceManagement.Models.Thuong", "Thuong")
                        .WithMany("ThuongNhanViens")
                        .HasForeignKey("ThuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("Thuong");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.TrinhDoHocVan", b =>
                {
                    b.HasOne("HumanResourceManagement.Models.NhanVien", "NhanVien")
                        .WithMany("TrinhDoHocVans")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.LichLam", b =>
                {
                    b.Navigation("ChamCongs");

                    b.Navigation("LichLamNhanViens");

                    b.Navigation("NghiVangs");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.NhanVien", b =>
                {
                    b.Navigation("ChamCongs");

                    b.Navigation("HieuSuats");

                    b.Navigation("HopDongs");

                    b.Navigation("LichLamNhanViens");

                    b.Navigation("Luongs");

                    b.Navigation("NghiVangs");

                    b.Navigation("PhuCapNhanViens");

                    b.Navigation("Thues");

                    b.Navigation("ThuongNhanViens");

                    b.Navigation("TrinhDoHocVans");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.PhongBan", b =>
                {
                    b.Navigation("ChucVus");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.PhuCap", b =>
                {
                    b.Navigation("PhuCapNhanViens");
                });

            modelBuilder.Entity("HumanResourceManagement.Models.Thuong", b =>
                {
                    b.Navigation("ThuongNhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
